---
  apiVersion: secrets.hashicorp.com/v1beta1
  kind: VaultStaticSecret
  metadata:
    name: awscreds-secret
  spec:
    vaultAuthRef: vault-auth
    mount: kvv2
    type: kv-v2
    path:  "aws/route53"
    refreshAfter: 10s
    destination:
      create: true
      name: awscreds